### ISSUE TITLE
Failed to import "openai"

### ISSUE THREAD

**Issue by yangyuan-zhen** [chrisyy2003/lingyin-bot#1]
12-08 13:08:10 [SUCCESS] nonebot | NoneBot is initializing...
12-08 13:08:10 [INFO] nonebot | Current Env: prod
12-08 13:08:11 [SUCCESS] nonebot | Succeeded to import "echo"
12-08 13:08:11 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
12-08 13:08:11 [ERROR] nonebot | Failed to import "openai"
Traceback (most recent call last):

**Comment by chrisyy2003** [comment]
更新了文档，重新拉取一下
