### ISSUE TITLE
能不能直接从镜像网站进行交流

### ISSUE THREAD

**Issue by MoKeNeng** [chrisyy2003/lingyin-bot#2]
能不能直接访问https://gpt.chatapi.art/这个镜像网站来进行chatgpt的交流，这样就不需要账号密码之类的东西来登入。

**Comment by chrisyy2003** [comment]
大家都用这个，这个网站压力也会很大的，而且现在都打不开

**Comment by MoKeNeng** [comment]
我可以打开额...可能网络问题吧。主要这个镜像网站不用登入，不用魔法，不用每天换taken。我觉得比较方便一点而已。谢谢大佬回复。
