### ISSUE TITLE
没问几个问题提示文本过长了。没有刷新会话的功能吗？

### ISSUE THREAD

**Issue by FTD499** [chrisyy2003/lingyin-bot#7]
发生错误: This model's maximum context length is 4097 tokens, however you requested 4339 tokens (1291 in your prompt; 3048 for the completion). Please reduce your prompt; or completion length.

**Comment by chrisyy2003** [comment]
把这个里的值改小一点。
![0642A670-9344-48DD-B454-3E307662FA61](https://user-images.githubusercontent.com/63803385/208232829-d8a6ef93-3cec-4cc7-a58a-cd8a2b33c005.png)
还在开发中，只是一个最基本的demon，有需求功能可以随时提

**Comment by chrisyy2003** [comment]
`pip install nonebot_plugin_gpt3 -U` 安装最行版
